zh translation
yearn/yearn-meta pull request #197
Opened 2022-03-23 04:09 UTC by xiaona423

translated in Chinerse

2022-03-23 18:03 UTC, DarkGhost7 requested changes

2022-03-23 18:03 UTC, DarkGhost7 commented on data/protocols/1/1inch.json
> +      "description": "1inch 是去中心化交易聚合器。1inch 在多个流动性池中找到最好的交易路径，提供给用户最佳的交易价格。"
`Instead of swapping tokens from a single DEX liquidity pool`
Wasnt translated

2022-03-23 19:08 UTC, Bee926 commented
Hello I am commenting on this :)

2022-03-23 20:36 UTC, Bee926 commented
1inch 是一个去中心化交易平台（DEX）聚合器。它可以提供用户最佳的交易价格。与其在单个 DEX 的流动性池中做代币交换，1inch 聚合不同池的交换并可以提供最高效的交易的建议。

@xiaona423

2022-03-24 05:43 UTC, DarkGhost7 approved these changes
lgtm

2022-03-24 05:48 UTC, DarkGhost7 approved these changes
lgtm

2022-03-24 05:48 UTC, merged

2022-04-20 21:26 UTC, Bee926 commented
done, good to go